<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Backbone.js Todos</title>
</head>
<body>
  <h1> Cat Tweets: </h1>
  <div id="example_content"></div>
  <script src="/modules/examples/backbone-js/js/lib/jquery-1.7.1.js"></script>
  <script src="/modules/examples/backbone-js/js/lib/underscore.js"></script>
  <script src="/modules/examples/backbone-js/js/lib/backbone.js"></script>
  <script src="/modules/examples/backbone-js/js/twitter.js"></script>
</body>
</html>
